name: Build and Test

on:
  workflow_dispatch:
    inputs:
      cpp_filename:
        description: 'Enter the name of the C++ file to build and test'
        required: true

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        os-version: [ ubuntu-latest ]
        compiler: [ latest, gcc-latest, gcc-10, g++-11, gcc-12, clang, clang-10, clang-11, clang++-12, clang++-14, clang++-15 ]

    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}
      - name: Check compiler
        shell: bash
        env:
            CC: ${{ steps.install_cc.outputs.cc }}
            CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          $CC --version
          $CXX --version
      - name: Build and Test C++ File
        run: |
          g++ -o my_program ${{ github.workspace }}/${{ github.event.inputs.cpp_filename }}
          ./my_program  # Run the compiled program and capture output
