name: C++ Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++

    - name: Build and Run C++ Project
      run: |
        g++ 22L-8227\ OOP\ Project.cpp -o my_project
        ./my_project

    - name: Check Files Existence
      run: |
        ls -lh

    - name: Upload Build Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Project Artifacts
        path: |
          my_project
          22L-8227\ OOP\ Project.cpp
          *.txt